// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import path from "path";

config({ path: path.resolve(__dirname, "../../.env") });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "schema.prisma",
  migrations: {
    path: "migrations",
    seed: "npx tsx seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
