// ============================================================================
// BrokerOS — Curated Voice Personas & Multi-Dialect TTS Catalog
// ============================================================================

export const VOICE_TTS_CATALOG = [
  // ── Indian & Hinglish Voices ──
  {
    id: 'sarvam-priya',
    name: 'Priya (Indic Hindi / Hinglish)',
    provider: 'sarvam',
    gender: 'Female',
    accent: 'Hindi / Hinglish',
    sampleAudio: 'https://storage.googleapis.com/brokeros-public/voices/priya-hi.mp3',
    description: 'Warm, consultative Hindi advisor. Ideal for pre-launch announcements and luxury site visit bookings.',
    previewText: 'Namaste! Skyline Realty me aapka swagat hai. Kya main aapko hamare naye luxury project ki details bata sakti hoon?',
    recommendedFor: ['Luxury Residential', 'Hinglish Leads', 'Pre-Sales'],
    tags: ['Luxury Residential', 'Hinglish Leads', 'Pre-Sales', 'Hindi', 'Indic'],
  },
  {
    id: 'sarvam-rahul',
    name: 'Rahul (Indic Hindi / English)',
    provider: 'sarvam',
    gender: 'Male',
    accent: 'Hindi / Indian English',
    sampleAudio: 'https://storage.googleapis.com/brokeros-public/voices/rahul-hi.mp3',
    description: 'Professional, assertive Hindi speaker with strong closing cadence for investor outreach.',
    previewText: 'Hello sir, main Skyline Realty se Rahul baat kar raha hoon. Hamare commercial investment options ke baare me baat karne ka yeh sahi samay hai?',
    recommendedFor: ['Commercial Leasing', 'Investor Outreach', 'Price Negotiation'],
    tags: ['Commercial Leasing', 'Investor Outreach', 'Price Negotiation', 'Hindi', 'Indic'],
  },
  {
    id: '11labs-viraj',
    name: 'Viraj (ElevenLabs Indian English)',
    provider: '11labs',
    gender: 'Male',
    accent: 'Indian English Professional',
    sampleAudio: 'https://storage.googleapis.com/eleven-public-prod/previews/models/eleven_multilingual_v2/iWNf11sz1GrUE4ppxTOL.mp3',
    description: 'Crisp Indian English tone with elite corporate warmth and natural cadence.',
    previewText: 'Good day! I am reaching out from Skyline Luxury Residences regarding your recent interest in our golf-facing penthouses.',
    recommendedFor: ['NRI Clients', 'Luxury Penthouses', 'Exclusive Previews'],
    tags: ['NRI Clients', 'Luxury Penthouses', 'Exclusive Previews', 'English', 'Indian'],
  },
  {
    id: '11labs-domi',
    name: 'Domi (ElevenLabs Warm Global)',
    provider: '11labs',
    gender: 'Female',
    accent: 'Indian / Global English',
    sampleAudio: 'https://storage.googleapis.com/eleven-public-prod/previews/models/eleven_multilingual_v2/AZnzlk1XvdvUeBnXmlld.mp3',
    description: 'Empathetic, clear, and reassuring tone. Excellent for following up on inbound inquiries.',
    previewText: 'Hello! Thank you for inquiring with us. I would love to assist you in finding your dream residence today.',
    recommendedFor: ['Inbound Follow-up', 'Site Visit Reminders', 'Feedback Collection'],
    tags: ['Inbound Follow-up', 'Site Visit Reminders', 'Feedback Collection', 'Warm', 'English'],
  },

  // ── Global English Voices ──
  {
    id: '11labs-rachel',
    name: 'Rachel (ElevenLabs Natural American)',
    provider: '11labs',
    gender: 'Female',
    accent: 'Neutral American',
    sampleAudio: 'https://storage.googleapis.com/eleven-public-prod/previews/models/eleven_multilingual_v2/21m00Tcm4TlvDq8ikWAM.mp3',
    description: 'Calm, executive American voice with high clarity and smooth conversational cadence.',
    previewText: 'Hello there, welcome to Skyline Luxury Estates. How may I assist your investment journey today?',
    recommendedFor: ['Global Buyers', 'High-Net-Worth Individuals', 'Concierge Booking'],
    tags: ['Global Buyers', 'High-Net-Worth Individuals', 'Concierge Booking', 'Executive', 'American'],
  },
  {
    id: '11labs-adam',
    name: 'Adam (ElevenLabs Authoritative American)',
    provider: '11labs',
    gender: 'Male',
    accent: 'Deep American',
    sampleAudio: 'https://storage.googleapis.com/eleven-public-prod/previews/models/eleven_multilingual_v2/pNInz6obpgDQGcFmaJgB.mp3',
    description: 'Authoritative, resonant male voice suited for executive commercial investment portfolios.',
    previewText: 'Good morning. I am calling from Skyline Commercial Real Estate regarding premium grade-A office space allocations.',
    recommendedFor: ['Commercial Properties', 'Institutional Investors', 'VIP Invitations'],
    tags: ['Commercial Properties', 'Institutional Investors', 'VIP Invitations', 'Deep', 'Authoritative'],
  },
  {
    id: 'cartesia-sarah',
    name: 'Sarah (Cartesia Ultra-Fast Sonic)',
    provider: 'cartesia',
    gender: 'Female',
    accent: 'Modern American',
    sampleAudio: 'https://storage.googleapis.com/brokeros-public/voices/sarah-cartesia.mp3',
    description: 'Sub-100ms response time with human-like breathing and natural interruptibility.',
    previewText: 'Hi! Quick question about your recent property inquiry — are you currently looking for 3 or 4 bedroom layouts?',
    recommendedFor: ['Rapid Qualification', 'Cold Lead Scrubbing', 'High Volume'],
    tags: ['Rapid Qualification', 'Cold Lead Scrubbing', 'High Volume', 'Fast', 'Sonic'],
  },
  {
    id: 'deepgram-orion',
    name: 'Orion (Deepgram Aura Crisp)',
    provider: 'deepgram',
    gender: 'Male',
    accent: 'Clear British / Neutral',
    sampleAudio: 'https://static.deepgram.com/audio/voices/orion.wav',
    description: 'High-definition conversational voice optimized for low latency and zero packet jitter.',
    previewText: 'Hello! I am calling to confirm your VIP preview tour appointment scheduled for this weekend.',
    recommendedFor: ['Payment Plan Clarification', 'Legal Verification Calls'],
    tags: ['Payment Plan Clarification', 'Legal Verification Calls', 'Clear', 'British'],
  },
] as const;
